{"name": "GET List of Users", "status": "failed", "statusDetails": {"message": "AssertionError: assert 401 == 200\n +  where 401 = <Response [401]>.status_code", "trace": "@allure.title(\"GET List of Users\")\n    @allure.severity(allure.severity_level.NORMAL)\n    def test_get_user_list():\n        url = f\"{BASE_URL}/users?page=2\"\n        response = requests.get(url, headers=get_headers())\n    \n>       assert response.status_code == 200\nE       assert 401 == 200\nE        +  where 401 = <Response [401]>.status_code\n\ntests/test_users_api.py:21: AssertionError"}, "start": 1751508631075, "stop": 1751508631836, "uuid": "612859fc-ad88-4a94-9c10-ee18e9bf5aad", "historyId": "b45224e861f4ec0f098cfbdb999f2556", "testCaseId": "b45224e861f4ec0f098cfbdb999f2556", "fullName": "tests.test_users_api#test_get_user_list", "labels": [{"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_users_api"}, {"name": "host", "value": "codespaces-2886b5"}, {"name": "thread", "value": "5609-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_users_api"}]}